### ISSUE TITLE
Unable to Save SmartApp (MiLight Manager / MiThings) page after install / configuration

### ISSUE THREAD

**Issue by augiephillips** [cloudsyjared/SmartThings-MiLight#1]
Hey there, Jared - thanks for all of your hard work - I'm excited to get the new update installed and running. Do I need to completely delete the old devices I have in order to integrate them with the new SmartApp(s)? I'd prefer not to uninstall the devices from their current SmartApps. Regardless, I'm running into the following issue. Let me know if there's any other info I can provide.

I've installed the new SmartApp (MiLight Manager), added the hub name, MAC address (in the proper format) and named the zones appropriately. However, the following error code is returned and I cannot save my changes. Any ideas?

````
8e8cc1cd-359f-47dd-a1b0-ac1b550b6354  10:08:37 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
0a97a3ab-71b4-4d6d-8936-2bc1e34e5a86  10:08:34 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
5a3f8dc1-232b-4275-b0fd-519f00fbb38b  10:08:26 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
3f5bfdd4-b713-4b9b-a324-34fce032b9d2  10:08:12 AM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91
6889436f-b612-4e2c-b7b4-028d3a88f256  10:08:12 AM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91

**Comment by cloudsyjared** [comment]
Hey Augie,

Quick question -- did you enter 99.0 anywhere ?

**Comment by augiephillips** [comment]
I haven't entered 99 or 99.0 (or any numbers) anywhere. I'm not sure where that could be coming from.

**Comment by cloudsyjared** [comment]
When you are looking at the live logs there is a number with dashes to the far left. When you click on this on the line with an error, what device or app comes up

**Comment by augiephillips** [comment]
The device that comes up is the name that I've given the hub within the smart app (Living Room New Master).

You can see that the number with dashes is different on each line — it shows up as a separate instance of the hub device.

````
2cfcd279-b545-4c9d-b804-86bab0efb2c6  12:44:20 PM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91
a6eed7a4-8daa-490c-9a94-ea10143f059d  12:44:20 PM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91
2cfcd279-b545-4c9d-b804-86bab0efb2c6  12:44:15 PM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91
aa360041-9b22-445a-8514-03ebb7b8e479  12:44:15 PM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 9
````

![image](https://cloud.githubusercontent.com/assets/15692931/13556213/9ca72a64-e399-11e5-9b0e-1277ba8de06c.png)

**Comment by cloudsyjared** [comment]
Can you send me a screenshot of your setup? The part where you put in the mac, number of zones, and zone names. Btw, for the zone name fields, they probably should be named descriptive names, since those are how they are going to show up in the app. For example, the name of the hub would be "second floor hub" and the 4 zones could be "Kitchen", "Dining Room", "Bathroom", and "Hallway" (if all those were on the second floor). Then in your smartthings app you would have lights named Kitchen/Dining Room/Bathroom/Hallway which you could control via app or an Echo or other SmartApps.

**Comment by augiephillips** [comment]
![](https://files.slack.com/files-pri/T0LR18SHW-F0QSEQ50T/slack_for_ios_upload.png)


![](https://files.slack.com/files-pri/T0LR18SHW-F0QSK3BAM/slack_for_ios_upload.png)

**Comment by cloudsyjared** [comment]
So you would actually just put 2 zones then. The all bulbs is created automatically. Not sure if I need to reword the install instructions? 

So when you click done you get an error?

**Comment by augiephillips** [comment]
Correct, as-is I get an error (see below). I was also getting an error when I juts had two zones (I tried that before 4 zones). I tried two zones again, and got the following:

"MiThings is Now Installed & Automating"

![screen 3 - augiephillips](https://cloud.githubusercontent.com/assets/15692931/13575707/d883a9a2-e44f-11e5-948a-06903e5d2490.jpg)


Then, that green bar goes away and I have to click "Done" again and get the following error:

![screen 4 - augiephillips](https://cloud.githubusercontent.com/assets/15692931/13575720/e6929d28-e44f-11e5-92b2-9ef284bbc9b1.jpg)

If I click done, I get the error above. If I try to go back, the changes are unsaved and I'm back where I started. No switches are created.

**Comment by cloudsyjared** [comment]
Then in the logs, the errors show up. Are one of those errors related to the device named "Arc Lamp" or "End Table"

**Comment by augiephillips** [comment]
![image](https://cloud.githubusercontent.com/assets/15692931/13576236/55570008-e452-11e5-8f1b-a8ee0227ce73.png)

They actually come through as the name of the master.

**Comment by augiephillips** [comment]
![image](https://cloud.githubusercontent.com/assets/15692931/13576291/a0108682-e452-11e5-8b15-202ec20e94e4.png)

The same error ^^^ is returned for both the **green** and **red** banners from the screenshots above.

Here's what comes through when I leave changes unsaved and return to the SmartApps list page:
````

429ed5dd-5a52-46ca-90b0-e19bf7b92b5d  10:54:22 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
7e9ccb37-caaa-4b4b-a851-9bdbd898452d  10:53:53 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
f7545938-0dbf-4140-b2c3-98743646d973  10:53:27 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
429ed5dd-5a52-46ca-90b0-e19bf7b92b5d  10:53:22 AM: error error: java.lang.NumberFormatException: For input string: "99.0"
f001cc2b-a057-435c-b59a-aeb73c4bd68f  10:53:05 AM: debug Installed Hubs: MiThings
55924ad5-cc83-499c-85eb-54a629d03b51  10:52:54 AM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91
7e9ccb37-caaa-4b4b-a851-9bdbd898452d  10:52:53 AM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @ line 91

**Comment by cloudsyjared** [comment]
I think there is a weird conflict happening here with the two versions installed. 99.0 is a percentage that you would get back from a status update. Remove all the outdated versions of the devices/apps and reinstall from scratch.

**Comment by cloudsyjared** [comment]
Also FYI your mac address is not complete

**Comment by augiephillips** [comment]
Fixed the MAC address.. thanks for the heads up. I'm not sure how that got lost in translation.

Yeah, I suspected that this had something to do with the two versions.. At some point this evening or tomorrow morning I will unlink the old devices/versions from all of their SmartApps ( :cry: ) and reinstall with the new version. I'm sure it'll likely resolve these issues.

Thanks, as usual, for all of your hard work and help :+1: .

I'll report back soon.

**Comment by cloudsyjared** [comment]
Any word on this ?

**Comment by augiephillips** [comment]
Sorry for the delay on this, have been out of town every weekend for the past month.

Going to try and do this now. Will check in this evening or tomorrow.

**Comment by cloudsyjared** [comment]
No response, closing.

**Comment by augiephillips** [comment]
Sorry, the system has been down with what's going on with ST. Thanks for your patience. 

AP

**Comment by augiephillips** [comment]
Got it all working - took completely deleting all devices and SmartApps, then re-installing. 

For anyone who eventually reads this, you must delete MiThings before you can delete the other SmartApp. 

Cheers, Jared.  Thanks for all of your hard work. Let me know what your PayPal account is. 👍🏽

**Comment by cloudsyjared** [comment]
Eventually this is going to get big enough to where I'll probably not be able to cover the hosting expenses myself. To the point of some choice users on the forums, what it's running on now just won't cut it for a hundred + users. When that time comes, I may ask the users to buy me a pint a month, and in return provide 99.5% uptime on the service + addtl features. For now though, continued testing and bug reporting is all I need.

**Comment by rhamblen** [comment]
Happy with that, but maybe an annual or lifetime donation would be nice too.
