### ISSUE TITLE
How to set color using automation

### ISSUE THREAD

**Issue by jg506** [cloudsyjared/SmartThings-MiLight#10]
Hi,

I installed today and mostly it is working well.  The bulbs are the 2016 RGBWW bulbs so you can add them your list of supported bulbs.
From the Things I can control everything - on/off dimming as well setting a color, however from other smart apps (such as ST own Light Automation) I can only turn on off and set dimming level. I am unable to set color. First the window that I get to set color does not have the color picker that is there in the Thing - instead it has list of predefined colors. Second, none of the color actually work the bulb stays on warm white.

Regards,
JG

**Comment by jg506** [comment]
Here are logs. The first opreation is color change using a button smart app. The second opreation is color change using the device native color picker. The bulb change colors only using the device color pciker but not via Smart Apps 
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:32 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@69df07c #9013FE
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:32 PM: debug MiLight device: AC:CF:23:A6:C9:F2, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#9013FE, color:232, notify:[message:, title:, hasMessage:0, image:], power:on]
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:32 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/color/#9013FE/2
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:32 PM: debug Zone switch color change! #9013FE!
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:24 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@d96f9d1 #7ED321
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:24 PM: debug MiLight device: AC:CF:23:A6:C9:F2, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#7ED321, color:107, notify:[message:, title:, hasMessage:0, image:], power:on]
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/color/#7ED321/2
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Zone switch color change! #7ED321!
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:24 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@5103f363 on
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:24 PM: debug MiLight device: AC:CF:23:A6:C9:F2, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#7ED321, color:107, notify:[message:, title:, hasMessage:0, image:], power:on]
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/power/on/2
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Zone switch changed state! on!
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, differences detected between color, updating. CLOUD: #7ED321 / DEVICE: null
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@438e0e58 on
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#7ED321, color:107, notify:[message:, title:, hasMessage:0, image:], power:on]
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/power/on/2
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Zone switch changed state! on!
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Zone switch changed state! off!
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug getChildDevices(false), children=3
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@6e86f4a5 off
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#9013FE, color:232, notify:[message:, title:, hasMessage:0, image:], power:off]
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/power/off/0
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug master switch off! AC:CF:23:A6:C9:F2 / Living Room MyLight Hub
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: error error: groovyx.net.http.HttpResponseException: Not Acceptable
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug MiLight device: AC:CF:23:A6:C9:F2, built path: rgbw/color/null/2
1ab50c68-d546-45b8-9c8c-adb2e5d8eecf  8:07:23 PM: debug Zone switch color change! null!

**Comment by cloudsyjared** [comment]
Yea, this is a known feature that is missing. I don't know yet what smart things is doing/sending when it sends "red", for example.

Unfortunately the stability of the platform is still my #1 priority. I'll get to this once the uptime gets better.

**Comment by jg506** [comment]
Thanks do you a rough ETA for this so I know if I should all my bulbs Mi-Light or Phillips Hue?
FYI:
This is how ST "Smart Light" app sends Red to your device:
setColor([switch:on, hue:100, saturation:100, level:100])
This is how ST "Smart Light" app sends Orange to your device:
setColor([switch:on, hue:10, saturation:100, level:100]) 
This is how you send Red
setColor({"red":208,"level":81.5686285495758,"hex":"#D0021B","blue":27,"saturation":99.03846149454748,"hue":97.97734629072242,"green":2,"alpha":1})

**Comment by jg506** [comment]
I was able to find a workaround and send RGB instead of the above hue using a different smartapp that allow sending RGB.

**Comment by jg506** [comment]
So it seems like ST can send colors either in RGB format or HSB format. Most of the Smartapps use HSB and not RGB.  When ST sends HSB your device does not understand it. Take a look at code here for from RGB to HSB conversion. https://github.com/KristopherKubicki/smartapp-color-temperature

HSB is sometimes called HSV. Also after looking at commands it seems the B (brightness) in ST is called "level"

**Comment by cloudsyjared** [comment]
"Thanks do you a rough ETA for this so I know if I should all my bulbs Mi-Light or Phillips Hue?"

You are of course welcome to write the smart things app code to convert hue/saturation to hex and submit a pull request. Otherwise I'm sure you won't be disappointed with the hue bulbs -- they have the support of a billion dollar company behind them. 

I don't give etas because this is a free project that I make no money off of and work on in my spare time. I'm sure you will be happy with the hue bulbs...

**Comment by cloudsyjared** [comment]
Closing!
