### ISSUE TITLE
MiLight WIFI-CON error when trying to set Cloud Server

### ISSUE THREAD

**Issue by Ruppie** [cloudsyjared/SmartThings-MiLight#12]
Hello,

Using the LimitlessLED v5+ tool, I have found my MiLight WIFI-CON bridge and set it to a fixed IP address.  All of the commands on the WIFI-CON seem to be responsive except for the Cloud Server commands.  I consistently see error result +ERR=-2.

Web access to the WIFI-CON (http://192.168.1.179/CN/management.html) shows firmware version 4.02.08T.25.

Get Cloud Server command log:
Scan for Wifi Bridges... Total will be 2.0 seconds.
Broadcast: UDP 5 times at 20ms intervals (100ms): Link_Wi-Fi
Waiting for responses for 1000ms up to 20 limitessled wifi bridges...
Response received IP and MAC address: 192.168.1.179,ACCF23045BD0,
Scan completed. 1 Wifi bridge/s found.
Send StartAdmin command to 192.168.1.179... +ok
Sent Command to 192.168.1.179:48899... AT+SOCKB
Waiting for response...
Received: +ERR=-2
Send QuitAdmin command to 192.168.1.179... AT+Q
Finished.

Enable Cloud Server command log:
Scan for Wifi Bridges... Total will be 2.0 seconds.
Broadcast: UDP 5 times at 20ms intervals (100ms): Link_Wi-Fi
Waiting for responses for 1000ms up to 20 limitessled wifi bridges...
Response received IP and MAC address: 192.168.1.179,ACCF23045BD0,
Scan completed. 1 Wifi bridge/s found.
Send StartAdmin command to 192.168.1.179... +ok
Sent Command to 192.168.1.179:48899... AT+SOCKB=TCP,38899,www.anymilight.com
Waiting for response...
Received: +ERR=-2
Send QuitAdmin command to 192.168.1.179... AT+Q
Finished.

Set Cloud Server command log:
Scan for Wifi Bridges... Total will be 2.0 seconds.
Broadcast: UDP 5 times at 20ms intervals (100ms): Link_Wi-Fi
Waiting for responses for 1000ms up to 20 limitessled wifi bridges...
Response received IP and MAC address: 192.168.1.179,ACCF23045BD0,
Scan completed. 1 Wifi bridge/s found.
Send StartAdmin command to 192.168.1.179... +ok
Sent Command to 192.168.1.179:48899... AT+SOCKB=TCP,38899,lights.cloudsy.com
Waiting for response...
Received: +ERR=-2
Send QuitAdmin command to 192.168.1.179... AT+Q
Finished.

Subsequent Get Cloud Server command gives the same response above.  Any hints on getting through this ERR=-2?  superbrightleds.com was no help at all.

Thanks,
Ruppie

**Comment by cloudsyjared** [comment]
Sorry, can't help here. I am only the author of the SmartThings app/device code and API for now. I do have plans to write my own configure app, but I have no ETA on that.

**Comment by nzhome** [comment]
ERR=-2  means its not a www.limitlessled.com wifi bridge v5. i.e the feature has not been programmed into your bridge. you probably have one of the older unreliable wifi bridges.

**Comment by cloudsyjared** [comment]
@nzhome thanks, that's helpful. lets chat..

**Comment by cloudsyjared** [comment]
@nzhome I looked at your GH account, looks like you've worked with this stuff pretty close. How can we chat about this ? Would like to see what you're doing with these bulbs!

**Comment by ARK1988** [comment]
Hi

After finding mi.light bridge, I sent "+ok" to it, and received +ERR=-1!
After that I sent "AT+WSCAN\r" and again received +ERR=-1!
Why this has happened?

tnx a lot
