### ISSUE TITLE
V5 Bridge and MAC

### ISSUE THREAD

**Issue by gdbgeek** [cloudsyjared/SmartThings-MiLight#5]
Jared, have you tried any of this with a newish WiFi bridge? I have a new V5 bridge from Limitless and the MAC I see locally isn't the same as the MAC that is being sent to the server.

**Comment by cloudsyjared** [comment]
Hi, no, I haven't. Where can I learn about the new bridge? I have an idea of what the problem is..

**Comment by gdbgeek** [comment]
Jared, thanks for the reply. Actually I've done more testing and the behaviour is consistent across bridge versions. What I'm seeing with my (server) app is that the local MAC I see in the MiLight app is different to the one the bridge sends the server. For example if my bridge MAC ends with 9E the server gets 9F (ie the last octet is incremented by 1). I had a look through your code but couldn't see any handling of this. Am I going crazy, is my code bad or is this consistent with your experience?

**Comment by cloudsyjared** [comment]
Hmm yea that's strange sorry I can't help you there.
