### ISSUE TITLE
Issue with Lights

### ISSUE THREAD

**Issue by kellydarren** [cloudsyjared/SmartThings-MiLight#6]
Jared
My setup stopped working the last few days.  I eventually reinstalled everything from the beginning but still having an issue.   The error that I've encountered is below !!!
Can you assist?

Thanks
Darren
**Hub Error**
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:55: error error: java.net.SocketTimeoutException: Read timed out
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:45: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/on/3
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:45: debug Zone switch changed state! on!
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:51: error error: java.net.SocketTimeoutException: Read timed out
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:41: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/off/3
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:38:41: debug Zone switch changed state! off!

**Light Error**
7f8f8c74-a7fd-4d18-abd2-7f6d12ef5b25  22:40:15: error groovy.lang.MissingMethodException: No signature of method: script14630892150601055917622.refresh() is applicable for argument types: () values: []
Possible solutions: redirect(java.util.Map), render(java.util.Map), every(), parse(java.lang.String), every(groovy.lang.Closure), pages() @ line 65
7f8f8c74-a7fd-4d18-abd2-7f6d12ef5b25  22:40:08: error groovy.lang.MissingMethodException: No signature of method: script14630892080921055917622.refresh() is applicable for argument types: () values: []
Possible solutions: redirect(java.util.Map), render(java.util.Map), every(), parse(java.lang.String), every(groovy.lang.Closure), pages() @ line 65

**Comment by cloudsyjared** [comment]
Thanks for the heads up, my server had crashed. Been working on a better solution for the past few weeks. Should have it released soon.

**Comment by cloudsyjared** [comment]
Sorry for the issues guys. I don't have another hub + bulbs to do dev work on, so doing actual upgrades is painful for everyone. I'll leave it untouched for a week or two before trying to get the new cloud code upgraded again.
