### ISSUE TITLE
Help Please Jared

### ISSUE THREAD

**Issue by wilddoghogg** [cloudsyjared/SmartThings-MiLight#8]
Hi there,
First off - massive thanks for the amazing work you are doing and apologies in advance for my relative newbie-ness, but I am unable to get the new code working.
I am a UK user and therefore unable to take advantage of the GitHub integration to SmartThings. I have therefore manually copied and pasted the code from your latest SmartApps and Device Handlers. I have followed the install instructions to the letter - with the following exceptions:-
1. I set the MiLight hubs back from TCP to UDP (the bulbs work fine from the native app now)
2. I created the device hanlder by copying and pasting the code. As per above - due to my being in the UK I was unable to use the integration. I published the device "for me"
3. I created the SmartApp for MiLight Manager (by copying and pasting - due to lack of GitHub integration). I published the SmartApp "for me"
4.I created the SmartApp for MiThings (by copying and pasting - due to lack of GitHub integration). I published the SmartApp "for me"
5.From the SmartThings app - I configured the SmartApp zones as per hub details.

Everything should work fine but for some reason it doesnt?! When I go into live logging from the website - I see absolutely NOTHING happening. I have enabled debugging on the SmartApp - but am not sure where that log goes for me to be able to send it to you.

I have tried to be as thorough as possible with this to give you as much info as possible. If there are any gaps please let me know and I will fill them. You help would be greatly appreciated mate!
cheers,

Will

**Comment by cloudsyjared** [comment]
Looking into it, not sure what happened between yesterday and today.

**Comment by cloudsyjared** [comment]
My load balancer was not forwarding traffic, will need to look into it some more when I have time. Is it working now?

**Comment by augiephillips** [comment]
Looks like it's working!! Cheers, Jared.

I gotta buy you several beers sometime.

**Comment by wilddoghogg** [comment]
It's now working for me too Jared, thank you - superstar!

**Comment by kellydarren** [comment]
It came back on for me also late last nite, late being in the wee hours of GMT time :-)

**Comment by cloudsyjared** [comment]
Just let me know if it goes down again. I have my only hub pointing to my development endpoint and so I don't know if there is a problem with the production deployment

**Comment by wilddoghogg** [comment]
Hi Jared,

Getting the below now:-

error: org.apache.http.conn.HttpHostConnectException: Connect to
lights.cloudsy.com:80 [lights.cloudsy.com/104.236.41.27] failed: Connection
refused

Is there an issue with your host?

**Comment by cloudsyjared** [comment]
Yeah trying to do an upgrade and it failed when all 60+ of the MiLight 
hubs connected. I had to roll back.

**Comment by cloudsyjared** [comment]
Sorry for the issues guys. I don't have another hub + bulbs to do dev work on, so doing actual upgrades is painful for everyone. I'll leave it untouched for a week or two before trying to get the new cloud code upgraded again.
